// lib/export.js — package the translated book into DOCX or PDF.
//
// DOCX is generated by hand (a docx is just a zip of XML) — no dependencies.
// PDF is rendered from a small RTL HTML page by headless Google Chrome, which
// shapes Persian correctly (Noto Naskh Arabic is present on this system).

const { execFile } = require('child_process');
const fs = require('fs');
const path = require('path');
const yazl = require('yazl');

function xmlEscape(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// Extract ordered blocks (headings + paragraphs) from a translated XHTML file.
function extractBlocks(xhtml) {
  const blocks = [];
  const re = /<(p|h[1-6])\b[^>]*>([\s\S]*?)<\/\1>/gi;
  let m;
  while ((m = re.exec(xhtml))) {
    const tag = m[1].toLowerCase();
    const text = m[2]
      .replace(/<[^>]+>/g, ' ')
      .replace(/&nbsp;/gi, ' ')
      .replace(/&amp;/gi, '&')
      .replace(/&lt;/gi, '<')
      .replace(/&gt;/gi, '>')
      .replace(/&quot;/gi, '"')
      .replace(/&#39;/gi, "'")
      .replace(/&#(\d+);/g, (mm, n) => String.fromCharCode(parseInt(n, 10)))
      .replace(/\s+/g, ' ')
      .trim();
    if (text) blocks.push({ type: tag[0] === 'h' ? 'h' : 'p', level: tag[1] ? parseInt(tag[1], 10) : 1, text });
  }
  return blocks;
}

function collectBlocks(files, getBytes) {
  const chapters = [];
  for (const name of files) {
    const xhtml = getBytes(name).toString('utf8');
    const blocks = extractBlocks(xhtml);
    if (blocks.length) chapters.push({ file: name, blocks });
  }
  return chapters;
}

// ---------- DOCX ----------

function writeDocxZip(parts, outPath) {
  return new Promise((resolve, reject) => {
    const zip = new yazl.ZipFile();
    const out = fs.createWriteStream(outPath);
    out.on('close', resolve);
    out.on('error', reject);
    for (const { name, data } of parts) zip.addBuffer(Buffer.from(data), name, { compress: true });
    zip.end();
    zip.outputStream.pipe(out);
  });
}

function buildDocx({ files, getBytes, outPath }) {
  const chapters = collectBlocks(files, getBytes);
  const body = [];
  for (const ch of chapters) {
    for (const b of ch.blocks) {
      const text = xmlEscape(b.text);
      if (b.type === 'h') {
        body.push(
          `<w:p><w:pPr><w:spacing w:before="240" w:after="120"/><w:rPr><w:b/><w:rtl/></w:rPr></w:pPr>` +
          `<w:r><w:rPr><w:b/><w:rtl/></w:rPr><w:t xml:space="preserve">${text}</w:t></w:r></w:p>`
        );
      } else {
        body.push(
          `<w:p><w:pPr><w:rPr><w:rtl/></w:rPr></w:pPr>` +
          `<w:r><w:rPr><w:rtl/></w:rPr><w:t xml:space="preserve">${text}</w:t></w:r></w:p>`
        );
      }
    }
  }
  const documentXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>
${body.join('\n')}
<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr>
</w:body></w:document>`;

  const parts = [
    { name: '[Content_Types].xml', data: CT },
    { name: '_rels/.rels', data: ROOT_RELS },
    { name: 'word/document.xml', data: documentXml },
    { name: 'word/_rels/document.xml.rels', data: DOC_RELS },
    { name: 'word/styles.xml', data: STYLES },
    { name: 'docProps/core.xml', data: CORE },
    { name: 'docProps/app.xml', data: APP },
  ];
  return writeDocxZip(parts, outPath);
}

const CT = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
<Default Extension="xml" ContentType="application/xml"/>
<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
<Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
<Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
</Types>`;

const ROOT_RELS = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
<Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>
</Relationships>`;

const DOC_RELS = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
</Relationships>`;

const STYLES = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
<w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Noto Naskh Arabic" w:hAnsi="Noto Naskh Arabic" w:cs="Noto Naskh Arabic"/><w:sz w:val="24"/></w:rPr></w:rPrDefault></w:docDefaults>
<w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style>
</w:styles>`;

const CORE = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>The Fountain (Persian)</dc:title><dc:language>fa-IR</dc:language></cp:coreProperties>`;

const APP = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"><Application>The Fountain</Application></Properties>`;

// ---------- PDF (headless Chrome) ----------

const PDF_CSS = `@page{size:A4;margin:2cm}
body{font-family:'Noto Naskh Arabic','Noto Sans Arabic',Tahoma,sans-serif;direction:rtl;text-align:right;font-size:12pt;line-height:1.9;color:#111;margin:0}
h1,h2,h3{font-weight:700;margin:1.4em 0 .6em;line-height:1.4}
h1{font-size:18pt}h2{font-size:15pt}h3{font-size:13pt}
p{margin:0 0 .9em;text-align:justify}`;

function buildPdf({ files, getBytes, title, outPath }) {
  const chapters = collectBlocks(files, getBytes);
  const parts = ['<!doctype html><html dir="rtl" lang="fa"><head><meta charset="utf-8"><title></title><style>'];
  parts.push(PDF_CSS);
  parts.push('</style></head><body>');
  for (const ch of chapters) {
    for (const b of ch.blocks) {
      if (b.type === 'h') {
        const level = Math.min(b.level, 3);
        parts.push(`<h${level}>${xmlEscape(b.text)}</h${level}>`);
      } else {
        parts.push(`<p>${xmlEscape(b.text)}</p>`);
      }
    }
  }
  parts.push('</body></html>');
  const htmlPath = outPath + '.html';
  fs.writeFileSync(htmlPath, parts.join('\n'));

  return new Promise((resolve, reject) => {
    const args = [
      '--headless=new',
      '--disable-gpu',
      '--no-sandbox',
      '--no-pdf-header-footer',
      `--print-to-pdf=${outPath}`,
      `file://${htmlPath}`,
    ];
    execFile('google-chrome', args, { timeout: 120000 }, (err, stdout, stderr) => {
      fs.unlink(htmlPath, () => {});
      if (err) return reject(new Error('Chrome PDF conversion failed: ' + (stderr || err.message)));
      resolve(outPath);
    });
  });
}

module.exports = { buildDocx, buildPdf, extractBlocks };
